# Project information
site_name: ZorgAPIs Developer Portal
site_description: API Library for Dutch Healthcare Developer Portal.
site_author: Nictiz
site_url: https://developer.zorgapis.nl/

# Repository
repo_url: https://github.com/nictiz/zorgapis-docs
edit_uri: blob/main/docs/

# Copyright
copyright: >-
  Copyright &copy; 2024 Nictiz | <a href="#__consent">Change cookie settings</a> |
  <a href="https://nictiz.nl/privacy-statement" target="_blank" rel="noopener">Privacy statement</a>

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - toc.follow
  font:
    text: Roboto
    code: JetBrains Mono

# Plugins
plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: nictiz/zorgapis-docs
      branch: main

# Additional configuration
extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better.
  analytics:
    provider: google
    property: G-VXC1C6H3RT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOc9XGTqkKKysztJPx5R7lh0TAskQHV_NW-PtaZ-6G6gXiWQ/viewform?entry.816166561={url}" target="_blank" rel="noopener">telling us what you're missing</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nictiz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nictiz/

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Page tree
nav:
  - Home:
    - index.md
    - Nictiz: nictiz.md
  - Learn:
      - learn/index.md
      - Authorizing a request: learn/authorizing-a-request.md
      - Organizations:
        - learn/organizations/index.md
        - Adding an organization: learn/organizations/adding-an-organization.md
        - Inviting a user to an organization: learn/organizations/inviting-a-user-to-an-organization.md
        - Accepting an invitation to join an organization: learn/organizations/accepting-an-invitation-to-join-an-organization.md
      - APIs:
        - learn/apis/index.md
        - Getting API requirements: learn/apis/getting-api-requirements.md
        - Adding an API specification: learn/apis/adding-an-api-specification.md
      - Standards:
        - learn/standards/index.md
        - Adding a communication standard: learn/standards/adding-a-communication-standard.md
        - Adding an information standard: learn/standards/adding-an-information-standard.md
      - Agreements:
        - learn/agreements/index.md
        - Adding a trust framework: learn/agreements/adding-a-trust-framework.md
  - Play:
    - play/index.md
  - Code: code/index.md
  - Blog:
      - blog/index.md
  - API Library: https://www.zorgapis.nl/